<br>
<h2>PRODUCTO MAS VENDIDO</h2>

<fieldset style="position:relative">
    <form action="/excel2/indicadoresventa_productos" method="post" target="_blank" >
        <ul>
            <li>
                <label>Año:</label>
                <select name="cmbAnio" required>
                    <option Value="2018">2018</option>
                    <option Value="2019">2019</option>
                    <option Value="2020">2020</option>
                </select>
            </li>
            <li>
                <input type="submit" value="Consultar">
            </li>
        </ul>
    </form>
</fieldset>