<script src="/javascript/submotivojs.js"></script>
<form action="/mantenimiento/actualizasubmotivodevolucion/" method="POST">
    <fieldset>
        <legend>Actualizaci&oacute;n de sub-motivo</legend>
        <ul>
            <li>
                <label>Motivo: </label>
                <select class="required" name="SubMotivo[tipo]" id="idmotivodevolucion">
                    <option value="<?php echo $SubMotivo[0]['tipo']?>"><?php echo '' . $MotivoDevolucion[$SubMotivo[0]['tipo']]; ?></option>
                    <?php for ($i = 1; $i <= count($MotivoDevolucion); $i++) { ?>
                        <option value="<?php echo $i ?>"><?php echo '' . $MotivoDevolucion[$i]; ?></option>
                    <?php } ?>
                </select>
            </li>
            <li>
                <label>Descripcion</label>
                <input type="text" value="<?php echo $SubMotivo[0]['descripcion'] ?>" name="SubMotivo[descripcion]" required="">
                <input type="hidden" value="<?php echo $_REQUEST['id'] ?>" name="idSubMot">
            </li>
            <li>
                <input type="submit" value="Actualizar">
            <li><button id="btnCancelar">Cancelar</button></li>
            </li>
        </ul>
    </fieldset>
</form>