<script type="text/javascript"src="/javascript/credenciales.js" ></script>
<h2 style="float:left !important;padding-bottom: 20px;width:100%">ASIGNAR CREDENCIALES</h2>

<fieldset>
    <ul style="text-align:center !important;width:100% !important;"><br>
		<li>
			<label>Nombre Usuario</label>
			<input type="text" id="txtActor1" class="uppercase" autofocus="on" size="40">
			<input type="hidden" id="txtIdActor1" val="0">
		</li>
        <li style="margin-left: 40px !important;">
			<label>Url Programa</label>
			<input type="text" id="txtModulo1" class="uppercase" autofocus="on" size="40">
			<input type="hidden" id="txtIdModulo1" val="0">
		</li>
		<li>
			<button id="btnBuscar">Buscar</button>
		</li>
	</ul>

</fieldset>

<fieldset style="text-align: center">
    <div id="loadCredenciales"></div>
</fieldset>
