<h2 style="float:left !important;padding-bottom: 20px;width:100%">Control Interno [Finalizado]</h2>
<br>

<style type="text/css">
    table {
        border: 1px solid;
        border-collapse: collapse;
        border-spacing:0px;
        padding: 0px;
        margin: 0px 0px 10px 0px;
    }
    table thead th {
        background: #d2e9fd;
        font-weight: bold;        
    }
    table thead td {
        background: #87c2f5;
        font-weight: bold;
        text-align: center;
        font-size: 15px;
    }
    table thead th, tfoot th {
        background: #d2e9fd;
        color: #000;
        text-align: center;
    }
    table tbody td {
        border: 1px solid #e2e0e6;
    }    
    .Reparado {
        font-weight: bold;
        color: blue;
        text-align: center;
    }
    .Descartado {
        font-weight: bold;
        color: red;
        text-align: center;
    }
    .Liberado {
        font-weight: bold;
        color: green;
        text-align: center;
    }
</style> 
    <form action="/serviciotecnico/controlinternofinalizado" method="post">
        <ul>
            <li>
                <b>Fecha Finalizacion: </b>
                <input style="background:skyblue;" type="text" name="txtFecha" value="<?php echo $Textfecha; ?>" class="datepicker">
            </li> 
            <li>
                    <button class="button">Consultar</button>
            </li>
        </ul>
    </form>
<hr><br>
<?php $tam = count($listado);
$idtecnico = -1;
for ($i = 0; $i < $tam; $i++) {
    if ($idtecnico != $listado[$i]['idtecnico']) { 
        if ($idtecnico != -1) {
            echo    '</tbody>' .
                '</table>';
        }
        echo '<table>' . 
                '<thead>' .
                    '<tr>' .
                        '<td colspan="10">' . $listado[$i]['nombretecnico'] . '</td> ' .
                    '</tr> ' .
                    '<tr> ' .
                        '<th>Nro</th>' .
                        '<th>Codigo</th>' .
                        '<th>Producto</th>' .
                        '<th>Fecha Inicio</th>' .
                        '<th>Fecha Fin</th>' .                
                        '<th>Situacion</th>' .
                        '<th>Imforme</th>' .
                        '<th>Accion</th>' .
                    '</tr>' .
                '</thead>' .
                '<tbody>';
        $idtecnico = $listado[$i]['idtecnico'];
    }
    echo '<tr>'
            . '<td>' . str_pad($listado[$i]['idcontrolinternost'], 6, 0, STR_PAD_LEFT) . '</td>'
            . '<td>' . $listado[$i]['codigopa'] . '</td>'
            . '<td>' . $listado[$i]['nompro'] . '</td>'
            . '<td>' . $listado[$i]['finicio'] . ' ' . $listado[$i]['horainicio'] . ':' . $listado[$i]['minutoinicio'] . '</td>'
            . '<td>' . $listado[$i]['ffin'] . ' ' . $listado[$i]['horafin'] . ':' . $listado[$i]['minutofin'] . '</td>'
            . '<td class="' . $SituacionReparacion[$listado[$i]['situacion']] . '">' . $SituacionReparacion[$listado[$i]['situacion']] . '</td>'
            . '<td style="width:40%">' . $listado[$i]['informe'] . '</td>'
            . '<td style="text-align: center;"><a href="/pdf/controlinternost/' . $listado[$i]['idcontrolinternost'] . '" target="_blank"><img src="/imagenes/iconos/pdf.gif"></a></td>'
        . '</tr>';
} 
if ($idtecnico != -1) {
    echo    '</tbody>' .
        '</table>';
}
?>        
    