<script src="/javascript/proveedor.js"></script>
<style>
    .block-contacto {
        width: 95%;
        background: #f5f5f5;
    }
    .bloque{
        float:left;
        margin : 10px;
        min-height: 500px;
        border : 1px dashed #444;
        padding: 5px;
        width: 40%;

    }
</style>
<h2>Nuevo Proveedor</h2>
<fieldset>
    <div class="bloque">	
        <h4>Datos Principales</h4>
        <form action="/proveedor/graba/" method="POST" >
            <ul class="inline-block">
                <li>
                    <label>Compañia:</label>
                    <input required type="text" placeholder="Nombre de la compañia" name="Proveedor[razonsocialp]" class="txtRSocial uppercase" size="50px">
                </li>
                <li>
                    <label>Direcci&oacute;n:</label>
                    <textarea  name="Proveedor[direccionp]" id="" cols="52" rows="4" class="required uppercase"></textarea>
                </li>
                <li>
                    <label>Descripci&oacute;n:</label>
                    <textarea   name="Proveedor[descripcionp]" id="" cols="52" rows="4" class="required uppercase"></textarea>
                </li>
                <li>
                    <label>Pagina Web:</label>
                    <input  type="text" placeholder="http://www.webdelaempresa.com" name="Proveedor[webp]">
                </li>
                <li>
                    <label>Tel&eacute;fono Principal:</label>
                    <input  type="text" placeholder="Teléfono de contacto principal" name="Proveedor[telefonop]">
                </li>
                <li>
                    <label>E-mail Principal:</label>
                    <input  type="text" placeholder="Email de uso frecuente" name="Proveedor[emailp]">
                </li>
                <li>
                    <label>Fax:</label>
                    <input  type="text" name="Proveedor[faxp]" maxlength="7">
                </li>
            </ul>
            <br>
            <ul class="inline-block block-contacto">
                <li>
                    <label>Persona:</label>
                    <input type="text" placeholder="Persona de contacto/Vendedor" name="Proveedor[contacto]" class="txtRSocial uppercase" size="50px">
                </li>
                <li>
                    <label>Cargo:</label>
                    <input type="text" placeholder="Cargo de la persona" name="Proveedor[cargo]" class="uppercase" size="50px">
                </li> 
                <li>
                    <label>E-mail:</label>
                    <input  type="text" placeholder="Email del vendedor" name="Proveedor[emailp2]" size="50px">
                </li>
                <li>
                    <label>Tel&eacute;fono:</label>
                    <input  type="text" placeholder="Teléfono de contacto del vendedor" name="Proveedor[telefonop2]" size="50px">
                </li>
            </ul>        
            <input type="hidden" name="Proveedor[tipoEmpresa]" value=2>
            <input type="hidden" name="Proveedor[idpais]" value=46>
            <br>
            <input type="submit" value="Registrar" class="btnRegistrar">
            <button id="btnCancelar">Cancelar</button>
        </form>
    </div>
</fieldset>