<!DOCTYPE HTML>
<html lang="en-ES">
<head>
    <meta charset="UTF-8">
        <link href="/css/bootstrap.css" rel="stylesheet" >
    <title>@CELESTIUM :: Grupo CELESTIUM</title>
    <link type="text/css" href="/css/login.css" rel="stylesheet" >
</head>
<body>
    
    <div id="bg_login">
        <div id="loginbox" style="margin-top:100px;" class="mainbox col-md-6 col-md-offset-4 col-sm-8 col-sm-offset-2">                    
            <div class="logo"></div>
            <div class="panel panel-info">
                    <div class="panel-heading">
                        
                        <div class="panel-title"><h2>INICIO</h2></div>
                        <div style="float:right; font-size: 80%; position: relative; top:-10px">login</div>
                    </div>     

                    <div style="padding-top:30px" class="panel-body">

                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                            
                       <div class="form"><?php include($path);?></div>
                        </div>                     
                    </div>  
        </div>
    </div>
</body>
</html>