<script src="/javascript/producto.js"></script>
<br><br>	

<a href="#" id="imprimir"><img src="/imagenes/imprimir.gif"></a>
<div id="contenedorImpresion">
	<h2>VALORIZADO POR LINEA</h2>
        <label for="txtFecha">Fecha</label>
        <form action="/producto/valorizaxlinea" method="post">
            <input type="text" class="datepicker" size="25" placeholder="Fecha" readonly="readonly" id="txtFecha" name="txtFecha" value="<?php echo $fechaseleccionada; ?>">
            &nbsp &nbsp &nbsp<input style="cursor: pointer" type="submit" class="button" value="Consultar" id="btnConsultar">
        </form>
        
        <!-- img id="idImgCargar" src="/imagenes/cargandofe.gif" width="20" high="20" -->
        <br><br>
<table id="idTablaValorizado">
		<tr>
			<th colspan="3">&nbsp;
		</th>

		</tr>
	<?php 
	$tam=count($datos);
	for ($j=0; $j < $tam; $j++) { 
		# code...
            if ($datos[$j]['valorizado']*1 < 1) {
                $datos[$j]['valorizado'] = 0;
            } else {
                $graf[$datos[$j]['nomlin']]=$datos[$j]['valorizado'];
                $total+=$datos[$j]['valorizado'];
            }
            
	}
	for ($i=0; $i < $tam; $i++) { 
            if ($datos[$i]['valorizado'] > 0) {
	?>
	<tr>
		<td><?php echo $datos[$i]['nomlin'];?></td>
		<td><?php echo " ".number_format($datos[$i]['valorizado'],2) . "\n";;?></td>
		<td rowspan="<?php echo $tam;?>" align="right">
			<?php if($i==0){
				$color = array( '#ccff00', '#7498e9', '#000faa',);
				$date=date('\a \l\a\s g:i a \d\e\l d.m.Y ');
				$grafico->setChartAttrs( 
					array( 	'type' => 'pie', 
							//'title' => 'VALORIZADO POR LINEA al: '.$fecha, 
							'title' => 'VALORIZADO POR CIF VENTAS '.$date, 
							'data' => $graf, 
							'size' => array( 550, 300 ), 
							'color' => $color));	
				echo $grafico;
			} ?>
		</td>
	</tr>
	<?php
        } }
	?>
	<tr>
		<td colspan="2"><hr></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td><?php echo "US $ ".number_format($total,2);?></td>
	</tr>	
</table> 
<?php  
// 			$color = array( '#95b645', '#7498e9', '#000fff',);
// 			$grafico->setChartAttrs( 
// 				array( 	'type' => 'pie', 
// 						//'title' => 'VALORIZADO POR LINEA al: '.$fecha, 
// 						'title' => 'VALORIZADO POR LINEA', 
// 						'data' => $graf, 
// 						'size' => array( 550, 300 ), 
// 						'color' => $color));	
// 			echo $grafico;
?>
</div>

