<script src="/javascript/reportletras.js" type="text/javascript"></script>
<script src="/javascript/clientesDestacados.js" type="text/javascript"></script>
<?php
$cantidadpadre = count($padre);
$cantidadhijo = count($hijo);
$cantidadzona = count($zona);
$cantidadtipo = count($tipocobranza);
$cantidadvendedor = count($vendedor);
$cantidadcobrador = count($cobrador);
?>
<style>
    .ocultar{
        display: none;
    }
</style>
<fieldset>
    <h2>CLIENTES :: DESTACADOS</h2>
    <br>
    <form action=""  method="POST" target="_blank" id="frmClientesDestacados">
        <ul>
            <a href="../../controllers/detallemovimientocontroller.php"></a>
            <li>
                <label for="">Zona Geografica:</label>
                <select name="lstCategoriaPrincipal" id="lstCategoriaPrincipal" >
                    <option value="">Zona Geografica</option>
                    <?php for ($i = 0; $i < $cantidadpadre - 1; $i++) { ?>
                        <option value="<?php echo $padre[$i]['idcategoria']; ?>"><?php echo $padre[$i]['nombrec']; ?></option>
                    <?php } ?>
                </select>
            </li>
            <li>
                <label for="">Region Cobranza:</label>
                <select id="lstCategoria"  name="lstCategoria" >
                    <option value="">Zona Cobranza-Categoria</option>
                    <?php for ($i = 0; $i < $cantidadhijo; $i++) { ?>
                        <option value="<?php echo $hijo[$i]['idcategoria']; ?>"><?php echo $hijo[$i]['nombrec']; ?></option>
                    <?php } ?>
                </select>
            </li>
            <li>
                <label for="">Zona:</label>
                <select id="lstZona"  name="lstZona">
                    <option value="">Zona Cobranza-Detalle</option>
                    <?php for ($i = 0; $i < $cantidadzona; $i++) { ?>
                        <option value="<?php echo $zona[$i]['idzona']; ?>"><?php echo $zona[$i]['nombrezona']; ?></option>
                    <?php } ?>
                </select>
            </li>
            <li>
                <label>Moneda:</label>
                <select name="cmbMoneda" id="cmbMoneda">                        
                    <option value="1">Soles (S/)</option>
                    <option value="2">Dolares (US $.)</option>
                </select>
            </li>
            <li>
                <label for="cmbDeuda">Monto:</label>
                <b id="textMoneda">S/</b>
                <select name="cmbMonto" id="cmbMonto">                        
                    <option value="5000">5000.00</option>
                    <option value="7000">7000.00</option>
                    <option value="10000">10000.00</option>
                    <option value="15000">15000.00</option>
                    <option value="">Otro Monto</option>
                </select>
            </li>
            <li class="blockMonto">
                <label for="txtmonto">Otro Monto:</label>
                <input type="text" id="txtMonto" name="txtmonto" size="10">
            </li>
        </ul>
        <br>
        <ul>
            <li>
                <button type="button" id="btnExcel">Consultar <img style="vertical-align: middle;text-align: center;" width="25" heigth="25" src="/imagenes/excel.png"> </button>
            </li>
        </ul>
    </form>
</fieldset>