
<script src="/javascript/listadocliente_actualizacion.js"></script>
<br><br>
<h2>LISTADO GENERAL (ACTUALIZACION)</h2>
<div id="listados">
    <ul>
        <li>
            <label>Busqueda:</label>
            <input style="background:skyblue;" type="text" id="txtCliente" name="txtBusqueda" title="Ingrese Razon Social o RUC " size="50px"/>
	</li>
        <li>
            <label id="idFiltro" data-dx="<?php echo '-1, ' . ($filtro == 3 ? ' 0, 1, 2' : $filtro); ?>">Filtro:</label>
            <label class="inline"><input type="checkbox" id="chkF1"<?php echo ($filtro==0 || $filtro==3? ' checked=""' : ''); ?>> No Actualizados</label>
            <label class="inline"><input type="checkbox" id="chkF2"<?php echo ($filtro==1 || $filtro==3? ' checked=""' : ''); ?>> Actualizados</label>
            <label class="inline"><input type="checkbox" id="chkF3"<?php echo ($filtro==2 || $filtro==3? ' checked=""' : ''); ?>> Para el Final</label>
        </li>
    </ul>

    <table id="tblresultado" style="display: none;">
        <thead>
            <tr>
                <th colspan="9">RESULTADOS SELECCIONADOS DE BUSQUEDA DE CLIENTES</th>
            </tr>
            <tr>
                <th>Id</th>
                <th>Razon Social</th>
                <th>documento</th>
                <th>Ubigeo</th>
                <th>Direcci&oacute;n</th>
                <th>Tel&eacute;fono</th>
                <th>Celular</th>
                <th>Estado</th>
                <th>Acci&oacute;n</th>
            </tr>
        </thead>
        <tbody>
            
        </tbody>
    </table>    
    
<table>
	<thead>
		<tr>
			<th colspan="7">Listado de Clientes No Actualizados</th>
                        <th colspan="2">
                            Filtro: 
                            <select id="filtro">
                                <option value="0"<?php echo ($filtro==0 ? 'selected' : ''); ?>>No Actualizados</option>
                                <option value="1"<?php echo ($filtro==1 ? 'selected' : ''); ?>>Actualizados</option>
                                <option value="2"<?php echo ($filtro==2 ? 'selected' : ''); ?>>Para el Final</option>
                                <option value="3"<?php echo ($filtro==3 ? 'selected' : ''); ?>>Listado General</option>
                            </select>
                        </th>
		</tr>	
		<tr>
			<th>Id</th>
			<th>Razon Social</th>
			<th>DNI</th>
			<th>RUC</th>
			<th>Zona</th>
			<th>Direcci&oacute;n</th>
			<th>Tel&eacute;fono</th>
			<th>Celular</th>
			<th>Acci&oacute;n</th>
		</tr>
	</thead>	
		<tbody>
		<?php
			for($i=0;$i<count($Cliente);$i++){
				echo "<tr>";
					echo "<td>".$Cliente[$i]['idcliente']."</td>";
					echo "<td>".$Cliente[$i]['razonsocial']."</td>";
					echo "<td>".$Cliente[$i]['dni']."</td>";
					echo "<td>".$Cliente[$i]['ruc']."</td>";
					echo "<td>".$Cliente[$i]['zona']. "</td>";
					echo "<td>".($Cliente[$i]['actualizado'] == 1 ? $Cliente[$i]['direccioncar'] : $Cliente[$i]['direccion'])."</td>";
					echo "<td>".($Cliente[$i]['actualizado'] == 1 ? $Cliente[$i]['telf'] : $Cliente[$i]['telefono']).$Cliente[$i]['telefono']."</td>";
					echo "<td>".($Cliente[$i]['actualizado'] == 1 ? $Cliente[$i]['cel'] : $Cliente[$i]['celular'])."</td>";
					echo "<td><a href=\"/cliente/actualizar/".$Cliente[$i]['idcliente']."\" class=\"btnEditar\"><img src=\"/imagenes/editnew.png\"></a></td>";
				echo "</tr>";
			}
		?>
		</tbody>
		<tfoot>
		<tr><td colspan="12" align="center">
		<?php
				if ($blockpaginas*10<$paginacion) {
					$blockpaginas=$blockpaginas+1;
				}else{
					$blockpaginas=$blockpaginas;
				}

				if ($pagina>1) 
				{
					echo "<a href=\"/cliente/desactualizados/".$filtro .".".($pagina-1)."\"> "."Anterior"." </a>";
				}
				
				for ($i=1; $i <=$blockpaginas ; $i++) { 
					$max=$i*10;

					for ($min=$max-9; $min <=$max ; $min++) { 
						if ($pagina>=$max-9 && $pagina<=$max && $paginacion>=$min) {
							if ($pagina==$min) {
								echo "<a href=\"/cliente/desactualizados/".$filtro .".".($min)."\"> <b style='color:blue;'>".($min)." </b></a>";
							}else{
								echo "<a href=\"/cliente/desactualizados/".$filtro .".".($min)."\"> ".($min)." </a>";
							}
						}
					}
				}

				if ($pagina<$paginacion) 
				{
					echo "<a href=\"/cliente/desactualizados/".$filtro .".".($pagina+1)."\"> "."Siguiente"." </a>";
				}

		?>
		<select id="seleccion" data-filtro="<?php echo $filtro; ?>">
			<option value=""></option>
			<?php  for ($i=1; $i <=$paginacion ; $i++) { ?>
				<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
			<?php } ?>
		</select>
		</tr>
	</tfoot>
</table>

</div>
