<script src="/javascript/clientevistageneral.js"></script>
<style>
    #AgendaModal {
        font-size: 13px;
    }
    .CuadroCliente {
        padding: 10px;
        border: 1px dotted #000;
        margin-bottom: 5px;
        
    }
    .CuadroCliente:not(h4) {
        font-size: 13px;
    }
    
    .CuadroCliente > h4 {
        color: #990000;
        margin-bottom: 5px;
    }
    
    .CuadroCliente > ul li > a {
        color: blue;
        font-size: 12px;
        font-weight: bold;
    }
    
    #modal > ul li > span {
        padding: 1px 10px;
        border: 1px solid #000;
    }
    
    .bloqueCuadro-2{
        background-color: #f5f5f5;
        padding: 5px;
        padding-left: 10px;
        font-size: 12px;
    }
    
    .bloqueCuadro-2 > center > a {
        color: blue;
        font-size: 12px;
        font-weight: bold;
    }
    
</style>
<div id="listados">
    <h2>Cliente ::: Listado Vista General</h2>
    <form method="POST" action="/cliente/buscaclientegeneral/" id="frmClienteVistaGeneral">
        <div id="busqueda">
            Razon Social o R.U.C.:
            <input type="text" id="txtBusqueda" name="txtBusqueda" title="Ingrese Razon Social o RUC " size="75px"/>
            <input type="submit" value="Buscar"/>
            <?php if (!empty($_REQUEST['txtBusqueda'])) { 
                echo "<br><b>Resultados de busqueda: </b>" . $_REQUEST['txtBusqueda'] . " <small><a href='/cliente/listavistageneral/' title='Eliminar Busqueda' style='color: #d60101 !important; font-weight: 700;'>(x)</a></small>";
            } ?>
        </div>
    </form>
    <table id="tblClientes">
        <thead>	
            <tr>
                <th>Razon Social</th>
                <th>DNI</th>
                <th>RUC</th>
                <th>Zona</th>
                <th>Direcci&oacute;n</th>
                <th>E-mail</th>
                <th>Teléfono</th>
                <th>Celular</th>
                <th>Accion</th>
            </tr>
        </thead>	
        <tbody>
            <?php
            for ($i = 0; $i < count($Cliente); $i++) {
                echo "<tr>";
                echo "<td>" . $Cliente[$i]['razonsocial'] . "</td>";
                echo "<td>" . $Cliente[$i]['dni'] . "</td>";
                echo "<td>" . $Cliente[$i]['ruc'] . "</td>";
                echo "<td>" . $Cliente[$i]['zona'] . "</td>";
                echo "<td>" . $Cliente[$i]['direccion'] . "</td>";
                echo "<td>" . $Cliente[$i]['email'] . "</td>";
                echo "<td>" . $Cliente[$i]['telefono'] . "</td>";
                echo "<td>" . $Cliente[$i]['celular'] . "</td>";
                echo "<td><a href='#' class='verDetalle' data-id='" . $Cliente[$i]['idcliente'] . "'><b>VER</b></a></td>";
                echo "</tr>";
            }
            ?>
        </tbody>
        <tfoot>
            <tr><td colspan="12" align="center">
                    <?php
                    $pagina = $_REQUEST['id'];
                    if ($blockpaginas * 10 < $paginacion) {
                        $blockpaginas = $blockpaginas + 1;
                    } else {
                        $blockpaginas = $blockpaginas;
                    }

                    if ($pagina > 1) {
                        echo "<a href=\"/cliente/listavistageneral/" . ($pagina - 1) . "\"> " . "Anterior" . " </a>";
                    }

                    for ($i = 1; $i <= $blockpaginas; $i++) {
                        $max = $i * 10;

                        for ($min = $max - 9; $min <= $max; $min++) {
                            if ($pagina >= $max - 9 && $pagina <= $max && $paginacion >= $min) {
                                if ($pagina == $min) {
                                    echo "<a href=\"/cliente/listavistageneral/" . ($min) . "\"> <b style='color:blue;'>" . ($min) . " </b></a>";
                                } else {
                                    echo "<a href=\"/cliente/listavistageneral/" . ($min) . "\"> " . ($min) . " </a>";
                                }
                            }
                        }
                    }

                    if ($pagina < $paginacion) {
                        echo "<a href=\"/cliente/listavistageneral/" . ($pagina + 1) . "\"> " . "Siguiente" . " </a>";
                    }
                    ?>
                    <select id="seleccion">
                        <option value=""></option>
                    <?php for ($i = 1; $i <= $paginacion; $i++) { ?>
                            <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                        <?php } ?>
                    </select>
            </tr>
        </tfoot>
    </table>
</div>

<div id="contenedorModal">
    <div class="bloqueCuadro-2">
        <center><a href="#" id="abrirAgendaModel">Añadir Medios de Contacto (+)</a></center>
    </div>
    <div id="modal">
    </div>
    <button id="imprimirModal"><img src="/imagenes/imprimir.gif"></button>
</div>

<div id="AgendaModal" data-id="-1">
    <b>CELULAR(ES): </b>
    <span id="DxAgendaCelular"></span>
    <a id="editarCelular" href="#"><img width="21" heigth="21" src="/imagenes/editar.gif"></a><br>
    <b><i id="lblCelular"> - Nuevo Celular: </i></b>
    <input type="text" value="" id="txtCelular">
    <a id="grabarCelular" href="#"><img width="21" heigth="21" src="/imagenes/grabar.gif"></a>
    <br><br><hr>
    
    <b>TELEFONO(S): </b>
    <span id="DxAgendaTelefono"></span>
    <a id="editarTelefono" href="#"><img width="21" heigth="21" src="/imagenes/editar.gif"></a><br>
    <b><i id="lblTelefono"> - Nuevo Telefono: </i></b>
    <input type="text" value="" id="txtTelefono">
    <a id="grabarTelefono" href="#"><img width="21" heigth="21" src="/imagenes/grabar.gif"></a>
    <br><br><hr>
    
    <b>E-MAIL(S): </b>
    <span id="DxAgendaEmail"></span>
    <a id="editarEmail" href="#"><img width="21" heigth="21" src="/imagenes/editar.gif"></a>
    <br>
    <b><i id="lblEmail"> - Nuevo Email: </i></b>
    <input type="text" value="" id="txtEmail">
    <a id="grabarEmail" href="#"><img width="21" heigth="21" src="/imagenes/grabar.gif"></a>
    <br><br><hr>

</div>