<h2 style="float:left !important;padding-bottom: 20px;width:100%">Clientes :: Relacionados</h2>
<br>
<div id="busqueda">
	Busqueda:<input type="text" id="txtClienteGlobal" name="txtCliente" size="50px" placeholder="Ingrese Razón Social o Nro RUC">
<input type="hidden" id="txtIdCliente" name="idcliente">
<br><br>
		Código:<input type="text" name="codigo" readonly id="codigo" disabled> 
		Razon Social:<input type="text" name="razonsocial" readonly id="razonsocial" size="40" disabled> 
		Número de RUC:<input type="text" name="ruc" readonly id="ruc" disabled>
		Codigo Dakkar:<input type="text" name="codantiguo" readonly id="codantiguo" disabled>
	</div>