<script src="/javascript/resumendekardex.js"></script>
<h2>Resumen de Kardex Por Producto</h2>
<fieldset>

    <form id="frmConsulta" method="post">
        <ul>
            <li>
                <label>Producto</label>
                <input autofocus="on" type="text" id="txtproducto" size="30" placeholder="Nombre o c&oacute;digo del producto">
                <input type="hidden" id="idProducto" name="txtproducto">
                <input type="text" id="txtDescripcion" size="80px" disabled readonly>
            </li>
        </ul>
        <br><br>
        <ul>
            <li>
                <label>Periodo</label>
                <select name="INICIOopcmes" id="INICIOmes">
                    <option value="01">Enero</option>
                    <option value="02">Febrero</option>
                    <option value="03" selected="selected">Marzo</option>
                    <option value="04">Abril</option>
                    <option value="05">Mayo</option>
                    <option value="06">Junio</option>
                    <option value="07">Julio</option>
                    <option value="08">Agosto</option>
                    <option value="09">Septiembre</option>
                    <option value="10">Octubre</option>
                    <option value="11">Noviembre</option>
                    <option value="12">Diciembre</option>
                </select>
            </li>
            <li>
                <select name="INICIOopcanho" id="INICIOanho">
                    <option value="2013">2013</option>
                    <option value="2014">2014</option>
                    <option value="2015">2015</option>
                    <option value="2016" selected="selected">2016</option>
                </select>
                 &nbsp; -
            </li>
            
            <li>
                <select name="FINopcmes" id="FINmes">
                    <option value="01">Enero</option>
                    <option value="02">Febrero</option>
                    <option value="03" selected="selected">Marzo</option>
                    <option value="04">Abril</option>
                    <option value="05">Mayo</option>
                    <option value="06">Junio</option>
                    <option value="07">Julio</option>
                    <option value="08">Agosto</option>
                    <option value="09">Septiembre</option>
                    <option value="10">Octubre</option>
                    <option value="11">Noviembre</option>
                    <option value="12">Diciembre</option>
                </select>
            </li>
            <li>
                <select name="FINopcanho" id="FINanho">
                    <option value="2013">2013</option>
                    <option value="2014">2014</option>
                    <option value="2015">2015</option>
                    <option value="2016" selected="selected">2016</option>
                </select>
            </li>
            
        </ul><br>
        <ul>
            <li><button id="btnConsultar" style="font-size: 18px;">Consultar <img style="vertical-align: middle;text-align: center;" width="25" heigth="25" src="/imagenes/consultar.png"></button></li>
            <li><button id="btnLimpiar" style="font-size: 18px;">Limpiar <img style="vertical-align: middle;text-align: center;" width="25" heigth="25" src="/imagenes/limpiar.png"> </button></li>
            <li><button id="btnImprimir" style="font-size: 18px;">Imprimir <img style="vertical-align: middle;text-align: center;" width="25" heigth="25" src="/imagenes/imprimir.gif"> </button></li>
        </ul>
    </form>
</fieldset>

<div id="ContenedorImpresion">
    <table id="tblEncabezado" style="display:none;">
        <tr><th colspan="6"><label id="lblTitulo">&nbsp;</label></th></tr>
        <tr>
            <th style="width:15%;">Desde</th><td><label id="lblmes"></label></td>
            <th style="width:15%;">Al</th><td><label id="lblanho"></label></td>
        </tr>
        <tr><th colspan="6"><img src="/imagenes/default-loader.gif" id="cargando"></th></tr>
    </table>
    <div id="tblConsulta">
    </div>
</div>