<?php
session_start();
$Producto = $_SESSION['Producto'];
?>
<script src="/javascript/jefedelinea.js"></script>
<form>
    <fieldset>
        <legend>Registro :: Jefe de Linea</legend>
        <ul class="inline-block">
            <li>
                <label>Vendedor:</label>
                <select class="required" id="opcJefes">
                    <option value="">Seleccione Vendedor</option>
                    <?php
                    for ($i = 0; $i < count($Vendedor); $i++) {
                        echo '<option value="' . $Vendedor[$i]['idactor'] . '">' . $Vendedor[$i]['nombreconcat'] . '</option>';
                    }
                    ?>
                </select>
                <button id="btnAnadir" type="button">Añadir</button>
            </li>            
        </ul>
    </fieldset>    
</form>
<fieldset>
    <table id="tblJefesdelinea">
        <thead>
            <tr>
                <th colspan="2">LISTADO JEFE DE LINEA</th>
            </tr>
            <tr>
                <th>Vendedor</th>
                <th>Jefe de Linea</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $tam = count($Jefes);
            for ($i = 0; $i < $tam; $i++) {
                echo "<tr id='idsjefe" . $Jefes[$i]['idactor'] . "' data-id='1'>" .
                        "<td><center>" . $Jefes[$i]['nombres'] . " " . $Jefes[$i]['apellidopaterno'] . " " . $Jefes[$i]['apellidomaterno'] . "</center></td>" .
                        "<td><center><input type='checkbox' class='chkJefe' data-id='" . $Jefes[$i]['idactor'] . "' checked></center></td>" .
                     "</tr>";
            }
            ?>
        </tbody>
    </table>
</fieldset>