<script src="/javascript/reporte-costodeproductos.js"></script>

<fieldset style="display:inline-block">
    <h2>REPORTE: COSTO DE PRODUCTOS</h2><br>
    <input type="submit" value="Mostrar" id="idMostrar">
    <a href="/pdf/costodeproductos" target="_blank"><input type="submit" value="Ver en PDF"></a>
    <a href="/excel/costodeproductos" target="_blank"><input type="submit" value="Ver en Excel"></a>
</fieldset>

<fieldset style="display:inline-block" id="contenidoCosto">
</fieldset>