<script src="/javascript/durezaproductos.js"></script>
<link rel="stylesheet" type="text/css" href="/css/select.css">

<h2>Dureza de Productos</h2>
<br>

<fieldset style="display:inline-block">
    <legend><b>Filtro</b></legend>

    <ul>
        <li>
            <label>Seleccione una de las opiones</label>
            <input type="radio" name="rbFiltro" value="3" checked="checked"> Por Linea
            &nbsp;<input type="radio" name="rbFiltro" value="4"> Por Sub Linea	
            &nbsp;<input type="radio" name="rbFiltro" value="5"> Por Producto
        </li>
        <li id="liFecha">
            <label>Fecha: </label>
            <input type="text" value="<?php echo date("Y/m/d"); ?>" style="background-color:skyblue" id="txtFechaInicio" name="txtFechaInicio" class="datepicker" readonly="readonly" placeholder="Fecha Actual" >
            <b>(Por defecto fecha actual)</b>
	</li>
        <li id="liStock">
            <label>Stock: </label>
            <select id="lstStock">
                <option value="1">Todos</option>
                <option value="2">Disponibles</option>
                <option value="3">Agotados</option>
            </select>
	</li>
        <br>
        <li id="liLinea">
            <label>Linea</label>
            <select id="lstLinea">
                    <option value="">-- Linea --</option>
                    <?php
                            for($i=0;$i<count($Linea);$i++){
                                    echo '<option value="'.$Linea[$i]['idlinea'].'">'.$Linea[$i]['nomlin'].'</option>';
                            }
                    ?>
            </select>
        </li>
        <li id="liSubLinea">
            <label>Sublinea</label>
            <select id="lstSubLinea">
                    <option value="">-- Sub Linea --</option>
            </select>
        </li>
        <li id="liProducto">
            <label>Producto</label>
            <input type="text" class="text-large required uppercase" placeholder="Ingrese Codigo o Nombre del Producto" id="txtCodigoProducto">
            <input type="hidden" id="txtIdProducto">
        </li>
        <li>
            <label>Formato</label>
            <select name="opcFormato" id="opcFormato">
                <option value="1">Tabla Dinámica</option>
                <option value="2">Cuadro General</option>
            </select>
        </li>
        <li id="buttomContent1">
            <button id="btnConsultar">Consultar</button>
        </li>
        <li>
            <form action="/pdf/durezaproducto/" method="post" target="_blank">
                <input type="submit" value="ver en pdf" id="mostrarPDF">
                <input type="hidden" id="idProducto" name="idProducto">
                <input type="hidden" id="idLinea" name="idLinea">
                <input type="hidden" id="idSubLinea" name="idSubLinea">
                <input type="hidden" id="fecha" name="fecha">
                <input type="hidden" id="idstockActual" name="stockactual">
            </form>
        </li>
    </ul>
</fieldset>

<table>
    <thead>
        <tr>
            <th colspan="6" style="background:#B4D1F7;color:#830E0E;"><h1><b>REPORTE - DUREZA DE PRODUCTOS</b></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th style='color:black;background:#C6DCF9;'><b>Almacen: </b></th><td><b id="idAlmacen">---</b></td>
            <th style='color:black;background:#C6DCF9;'><b>Fecha de Consulta: </b></th><td><b id="idFecha">---</b></td>
            <th style='color:black;background:#C6DCF9;'><b>Productos: </b></th><td><b id="idTextStock">---</b></td>
        </tr>
    </tbody>
</table>

<div id="tabladinamica">
    <table id="dataGridReport">
        <thead>
            <tr>
                <th data-field="codigo">CÓDIGO</th>
                <th data-field="nompro">PRODUCTO</th>
                <th data-field="nomlin">LINEA</th>
                <th data-field="nomsublin">SUB-LINEA</th>
                <th data-field="unidadmedida">U.M.</th>
                <th data-field="llegada">F. LLEGADA</th>
                <th data-field="inicial">S. INICIAL</th>
                <th data-field="disponible">S. DISPO</th>
                <th data-field="pvm">PVM</th>
                <th data-field="dureza">DUREZA(meses)</th>
            </tr>
        </thead>
    </table>
</div>

<div id="ContenidoCuadro" style="display: none">
    <form action="" id="from-seleccionado" target="_blank" method="POST">
        <table>
            <thead>
                <tr>
                    <th style='color:black;background:#C6DCF9;'>CÓDIGO</th>
                    <th style='color:black;background:#C6DCF9;'>PRODUCTO</th>
                    <th style='color:black;background:#C6DCF9;'>LINEA</th>
                    <th style='color:black;background:#C6DCF9;'>SUB-LINEA</th>
                    <th style='color:black;background:#C6DCF9;'>U.M.</th>
                    <th style='color:black;background:#C6DCF9;'>F. LLEGADA</th>
                    <th style='color:black;background:#C6DCF9;'>S. INICIAL</th>
                    <th style='color:black;background:#C6DCF9;'>S. DISPO</th>
                    <th style='color:black;background:#C6DCF9;'>PVM</th>
                    <th style='color:black;background:#C6DCF9;'>DUREZA(meses)</th>
                    <th style='color:black;background:#C6DCF9;'>
                        SELECCION<br>
                        <input type='checkbox' id='selecciontodoDureza'>
                    </th>
                </tr>
            </thead>
            <tbody id="ContenidoTabla">
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="11" align="right">
                        <input type="submit" value="Exportar a PDF" id="expPDFSel">
                        <input type="submit" value="Exportar a Excel" id="expEXCELSel">
                    </td>
                </tr>
            </tfoot>
        </table>
    </form>
</div>
