<!--<script type="text/javascript" src="/javascript/reporteCobranza.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>

<script type="text/javascript">
    $(function () {
        $('#container').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: {
                text: 'PERSONAS QUE DEBEN, 2015'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %'//,
                        style: {
                            color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                        }
                    }
                }
            },
            series: [{
                type: 'pie',
                name: 'Deudores',
                data: [ 
                            ['hola1', 50],
                            ['hola2', 20],
                            ['hola3', 30],

                ]
            }]
        });
    });
</script>

<h2>REPORTE::PORCENTAJE POR ZONA</h2>
<fieldset>
	<form id="frmCobranza" method="post">
	<ul>
		<li>
			<label>Zona Geografica</label>
			<select id="lstCategoriaPrincipal" name="lstCategoriaPrincipal" class="style">
				<option value="">----Zona Geografica----</option>
				<?php $cantidadZona=count($padre); ?>
				<?php for ($i=0; $i <$cantidadZona ; $i++) { ?>
				<option value="<?php echo $padre[$i]['idcategoria'] ?>"><?php echo $padre[$i]['nombrec'] ?></option>	
				<?php } ?>
			</select>
		</li>
		<li><p>
			<label>Zona Cobranza-Categoria</label>
			<select id="lstZonaCobranza" name="lstZonaCobranza" class="style">
				<option value="">Zona Cobranza-Categoria</option>
			</select></p>
		</li>
		<li>
			<label>Fecha Inicio</label>
			<input type="text" style="background-color:skyblue" id="txtFechaInicio" name="txtFechaInicio" class="datepicker" readonly="readonly" placeholder="F. Cancelado" >
		</li>
		<li>
			<label>Fecha Fin</label>
			<input type="text" style="background-color:skyblue" id="txtFechaFinal" name="txtFechaFinal" class="datepicker" readonly="readonly" placeholder="F. Cancelado" >
		</li>
                <li>
                    <label>Año</label>
                    <select id="lstAnio">
                        <option val="">Año</option>
                        <option val="2016">2016</option>
                        <option val="2015">2015</option>
                        <option val="2014">2014</option>
                        <option val="2013">2013</option>
                    </select>
                    
                </li>

	</ul><br>
	<ul>

		<li>
			<label>Vendedor</label>
			<input type="text" id="txtVendedor"  placeholder="Nombre Vendedor" size="50">
			<input type="hidden" id="idVendedor" name="idVendedor">
		</li>		
	</ul><br>
	<ul>
		<li><button id="btnConsultar" style="font-size: 18px;">Consultar <img style="vertical-align: middle;text-align: center;" width="25" heigth="25" src="/imagenes/consultar.png"></button></li>
                <li><a href="#" id="imprimir"><img src="/imagenes/imprimir.gif"></a></li>
	</ul>
	</form>
</fieldset>
<script src="javascript/Highcharts-4.1.5/js/highcharts.js"></script>
<script src="javascript/Highcharts-4.1.5/js/modules/exporting.js"></script>
<fieldset id="container">
</fieldset>-->




































<!--<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>-->
<script type="text/javascript">
//    google.charts.load('current', {'packages':['corechart']});
//    google.charts.setOnLoadCallback(drawChart);
//    function drawChart() {
//
//      var data = google.visualization.arrayToDataTable([
//        ['Task', 'Hours per Day'],
//        ['Work',     11],
//        ['Eat',      2],
//        ['Commute',  2],
//        ['Watch TV', 2],
//        ['Sleep',    7]
//      ]);
//
//      var options = {
//        title: 'My Daily Activities'
//      };
//
//      var chart = new google.visualization.PieChart(document.getElementById('piechart'));
//
//      chart.draw(data, options);
//    }
</script>
<script type="text/javascript" src="/javascript/reporteVenta1.js"></script>

<script src="/javascript/producto.js"></script>
<h2>REPORTE::PORCENTAJE POR ZONA</h2>
<fieldset>
	<form id="frmCobranza" method="post">
	<ul>
		<li>
			<label>Zona Geografica</label>
			<select id="lstCategoriaPrincipal" name="lstCategoriaPrincipal" class="style required">
				<option value="">----Zona Geografica----</option>
				<?php $cantidadZona=count($padre); ?>
				<?php for ($i=0; $i <$cantidadZona ; $i++) { ?>
				<option value="<?php echo $padre[$i]['idcategoria'] ?>"><?php echo $padre[$i]['nombrec'] ?></option>	
				<?php } ?>
			</select>
		</li>
		<li><p>
			<label>Zona Cobranza-Categoria</label>
			<select id="lstZonaCobranza" name="lstZonaCobranza" class="style">
				<option value="">---Zona Cobranza-Categoria---</option>
			</select></p>
		</li>
                <li>
                    <label>Zona</label>
                    <select id="lstZona" name="lstZona" class="style">
                        <option value="">---Zona---</option>
                    </select>
                </li>

		<li>
			<label>Fecha Inicio</label>
			<input type="text" style="background-color:skyblue" id="txtFechaInicio" name="txtFechaInicio" class="datepicker" readonly="readonly" placeholder="F. Cancelado" >
		</li>
		<li>
			<label>Fecha Fin</label>
			<input type="text" style="background-color:skyblue" id="txtFechaFinal" name="txtFechaFinal" class="datepicker" readonly="readonly" placeholder="F. Cancelado" >
		</li>
	</ul><br>
	<ul>

		<li>
			<label>Vendedor</label>
			<input type="text" id="txtVendedor"  placeholder="Nombre Vendedor" size="50">
			<input type="hidden" id="idVendedor" name="idVendedor">
		</li>		
	</ul><br>
	<ul>
		<li><button id="btnConsultarPorcentaje" style="font-size: 18px;">Consultar <img style="vertical-align: middle;text-align: center;" width="25" heigth="25" src="/imagenes/consultar.png"></button></li>
                <li><a href="#" id="btnImprimir"><img src="/imagenes/imprimir.gif"></a></li>
	</ul>
	</form>
</fieldset>

<fieldset id="contenedor">
    <div id="divReport" style='align-content: center;'>
    </div>
    <!--<div id="piechart" style="width: 900px; height: 500px;"></div>-->
</fieldset>


