<script src="/javascript/reporteVencidasVendedor.js" type="text/javascript"></script>
<script src="/javascript/reportletras.js" type="text/javascript"></script>
<script src="/javascript/wc_cliente.js" type="text/javascript"></script>
<script src="/javascript/wc_ordenventa.js" type="text/javascript"></script>
<?php
    $cantidadpadre = count($padre);
    $cantidadhijo = count($hijo);
    $cantidadzona = count($zona);
    $cantidadtipo = count($tipocobranza);
    $cantidadvendedor = count($vendedor);
    $cantidadcobrador = count($cobrador);
?>
<style>
    .ocultar{
        display: none;
    }
</style>
<fieldset>
    <h2>VENTAS VENCIDAS POR CONDICION DE VENTA POR VENDEDOR</h2>
    
    <form action="/excel/detalladodeletras"  method="POST" target="_blank" id="frmLetras" style='margin-top:15px;'>
        <ul>
            <li>
                <label for="txtFechaInicio">Fecha Vencimiento:</label>
                <input type="text" style="background: skyblue;width: 160" class="datepicker" size="35" placeholder="Fecha Inicio Vencimiento" readonly="readonly" id="txtFechaInicio" name="txtFechaInicio">
            </li>
            <li>
                <label for="txtFechaFinal">Fecha Vencimiento:</label>
                <input type="text" style="background: skyblue;width: 160" class="datepicker" size="35" placeholder="Fecha Final Vencimiento" readonly="readonly" id="txtFechaFinal" name="txtFechaFinal">
            </li>
            <li class="cls_power">
                <label for="">Zona Geografica:</label>
                <select name="lstCategoriaPrincipal" id="lstCategoriaPrincipal" >
                    <option value="">Zona Geografica</option>
                    <?php for ($i = 0; $i < $cantidadpadre - 1; $i++) { ?>
                        <option value="<?php echo $padre[$i]['idcategoria']; ?>"><?php echo $padre[$i]['nombrec']; ?></option>
                    <?php } ?>
                </select>
            </li>
            <li class="cls_power">
                <label for="">Region Cobranza:</label>
                <select id="lstCategoria"  name="lstCategoria" >
                    <option value="">Zona Cobranza-Categoria</option>
                    <?php for ($i = 0; $i < $cantidadhijo; $i++) { ?>
                        <option value="<?php echo $hijo[$i]['idcategoria']; ?>"><?php echo $hijo[$i]['nombrec']; ?></option>
                    <?php } ?>
                </select>
            </li>
            <li class="cls_power">
                <label for="">Zona:</label>
                <select id="lstZona"  name="lstZona">
                    <option value="">Zona Cobranza-Detalle</option>
                    <?php for ($i = 0; $i < $cantidadzona; $i++) { ?>
                        <option value="<?php echo $zona[$i]['idzona']; ?>"><?php echo $zona[$i]['nombrezona']; ?></option>
                    <?php } ?>
                </select>
            </li>
            <li class="cls_power">
                <label for="txtClientexIdCliente">Razon Social Cliente:</label>
                <input type="text" id="txtClientexIdCliente" name="txtClientexIdCliente" size="50">
                <input type="hidden" id="txtIdCliente" name="txtIdCliente">
            </li>
            <li>
                <select id="lstvendedor" name="lstvendedor" >
                    <option value="">Vendedor</option>
                    <?php for ($i = 0; $i < $cantidadvendedor; $i++) { ?>
                        <option value="<?php echo $vendedor[$i]['idactor']; ?>"><?php echo $vendedor[$i]['nombres'] . ' ' . $vendedor[$i]['apellidopaterno'] . ' ' . $vendedor[$i]['apellidomaterno']; ?></option>
                    <?php } ?>
                </select>
            </li>
            <li class="cls_power">
                <label for="txtOrdenVentaxId">Orden de Venta:</label>
                <input type="text" id="txtOrdenVentaxId" name="txtOrdenVentaxId" size="20">
                <input type="hidden" id="txtIdOrdenVenta" name="txtIdOrdenVenta">
            </li>
            <li class="ocultar">
                <label for="">Moneda:</label>
                <select name="lstMoneda" id="lstMoneda">
                    <option value=""> -- Seleccione -- </option>
                    <option value="1">Soles</option>
                    <option value="2">Dolares</option>
                </select>
            </li>
        </ul>
        <br>
        <ul>
            <li>
                <label for="">Especifique Detalle:</label>
                <select id="cmbCondicion" name="cmbCondicion">
                    <option value=""> -- Seleccione -- </option>
                    <option value="1">Letras</option>
                    <option value="2">Creditos</option>
                    <option value="3">Contado</option>
                </select>
            </li>
            <span id="groupLetras">
            <li >
                <input type="text" id="txtCondiciones" name="txtCondiciones" hidden="">
                <label for="" class="ocultar">Estado:</label>
                <select id="lstRecepcionLetras" name="lstRecepcionLetras" class="ocultar">
                    <option value=""> -- Seleccione -- </option>
                    <option value="1">Enviadas al Banco</option>
                    <option value="2">Sin enviar al Banco</option>
<!--                    <option value="3">Por Producto</option>-->
                    <option value="4">Protestadas</option>
                </select>
            </li>
            <li>
                <label for="">Estado:</label>
                <select id="cmbCondVencimiento1" name="lstEstadoLetrass" class="estadoVencida">
                    <option value=""> -- Seleccione -- </option>
                    <option value="1">Vencidas</option>
                    <option value="2">Por Vencer</option>
                </select>
            </li>
            </span>
        </ul>
        <ul id="groupVencimiento" >
            <li>
                <label for="">Estado:</label>
                <select id="cmbCondVencimiento1" name="lstEstado" class="estadoVencida">
                    <option value=""> -- Seleccione -- </option>
                    <option value="1">Vencidas</option>
                    <option value="2">Por Vencer</option>
                </select>
            </li>
            <li id="cmbCondVencimiento2">
                <label for="">Intervalo de tiempo:</label>
                <select name="lstCondVencimiento2">
                    <option value=""> -- Seleccione -- </option>
                    <option value="30">vencidos hace 30 dias </option>
                    <option value="60">vencidos hace 60 dias</option>
                    <option value="90">vencidos hace 90 dias</option>
                    <option value="91">vencidos en mas de 90 dias</option>
                </select>
            </li>
            <li id="cmbCondVencimiento3">
                <label for="">Intervalo de tiempo:</label>
                <select name="lstCondVencimiento3">
                    <option value=""> -- Seleccione -- </option>
                    <option value="30">por vencer en 30 dias </option>
                    <option value="60">por vencer en 60 dias</option>
                    <option value="90">por vencer en 90 dias</option>
                    <option value="91">por vencer en mas de 90 dias</option>
                </select>
            </li>
            <li style="display: none;">
                <input type="checkbox" name="chk1" id="chk1" >&nbsp;formato 1
                <input type="checkbox" name="chk2" id="chk2" style="margin-left:10px;"  checked="">&nbsp;formato 2
            </li>
        </ul>
        <br>
        <ul>
            <li>
                <button type="button" id="btnExcel">Detallado <img style="vertical-align: middle;text-align: center;" width="25" heigth="25" src="/imagenes/excel.png"> </button>
            </li>
            <li id="mostrarPowerAcoustik">
                <input type="checkbox" name="chk10" id="chk10"  checked="">&nbsp;formato 1
                <input type="checkbox" name="chk20" id="chk20" style="margin-left:10px;">&nbsp;formato 2
            </li>

<!--            <li>
                <button type="button" id="btnAnalisis">Análisis <img style="vertical-align: middle;text-align: center;" width="35" heigth="35" src="/imagenes/estadistico.png"> </button>
            </li>-->
        </ul>
    </form>
</fieldset>