<?php $idmodulo=141; require_once 'evalcredenciales.php'; ?>
<script type="text/javascript" src="/javascript/reporteInventario.js" ></script>
<br>
<h2 style="float:left !important;padding-bottom: 20px;width:100%">REPORTE :: INVENTARIO</h2>

<fieldset>
	<form action="/pdf/reporteInventario" method="post" target="_blank">
		<ul>
			<li>
				<?php $cantidadInventario=count($inventario); ?>
				<label>Inventario</label>
				<select id="lstInventario" name="lstInventario">
                    <?php if($evaluarCredenciales==1){ ?>
                        <?php if($c15_datashet!=$c14_datashet){ ?>
                            <?php for ($i=0; $i <$cantidadInventario ; $i++) { ?>
                                <?php  if ($c14_datashet==1 and  $inventario[$i]['invagrupamiento']==1){ ?>
                                    <option value="<?php echo $inventario[$i]['idinventario']; ?>" ><?php echo $inventario[$i]['codigoinv'].'  del  '.$inventario[$i]['fechainv']; ?></option>
                                <?php } ?>
                                <?php  if ($c14_datashet==0){ ?>
                                    <option value="<?php echo $inventario[$i]['idinventario']; ?>" ><?php echo $inventario[$i]['codigoinv'].'  del  '.$inventario[$i]['fechainv']; ?></option>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                    <?php if($evaluarCredenciales==0){ ?>
                        <?php for ($i=0; $i <$cantidadInventario ; $i++) { ?>
                            <?php  if ($inventario[$i]['invagrupamiento']==1){ ?>
                                <option value="<?php echo $inventario[$i]['idinventario']; ?>" ><?php echo $inventario[$i]['codigoinv'].'  del  '.$inventario[$i]['fechainv']; ?></option>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
				</select>
			</li>
			<li>
				<?php $cantidadBloques=count($bloques); ?>
				<label>Anaquel</label>
                <select id="lstBloques" name="lstBloques" style="width:150px;">
					<?php for ($i=0; $i <$cantidadBloques ; $i++) { ?>
						<option value="<?php echo $bloques[$i]['idbloque'] ?>" ><?php echo $bloques[$i]['codigo'] ?></option>
					<?php } ?>
				</select>
			</li>
			<li>
				<label>Codigo</label>
				<input type="text"  id="txtProducto"  style="width:130px;">
				<input type="hidden" id="idProducto" name="idProducto">
			</li>
			<li>
				<label>Descripcion</label>
				<input type="text" size="45" id="txtDescripcion" readonly>
			</li>
			<li>
				<input type="submit" value="Imprimir" id="btnConsultar">
			</li>
			<li>
				<button id="btnLimpiar">Limpiar</button>
			</li>

		</ul>
	</form>
</fieldset>