<fieldset>
    <h2>REPORTE :: Seguimiento Cobranzas</h2>
    <form action="/excel/seguimientocobranzas" method="post" target="_blank" id="frmConsulta">
        <ul>
            <li>
                <label for="txtFechaInicio">Fecha Inicio Guia</label>
                <input type="text" class="datepicker" size="25" placeholder="Fecha Inicio" readonly="readonly" id="txtFechaInicio" name="txtFechaInicio" required="">
            </li>
            <li>
                <label for="txtFechaFinal">Fecha Final Guia</label>
                <input type="text" class="datepicker" size="25" placeholder="Fecha Final" readonly="readonly" id="txtFechaFinal" name="txtFechaFinal" required="">
            </li>
            <li>
                <button type="submit">Consulta <img src="/imagenes/excel.png" alt="" width="25" height="25" style="vertical-align: middle"></button>
            </li>
        </ul>
    </form>
</fieldset>