<script src="/javascript/stockproducto.js"></script>
<h2>Reportes: Actualizacion de Productos</h2>
<br>
<fieldset style="display:inline-block">
	<legend>Filtro</legend>
	<ul>
		<li id="Producto">
			<label>Producto</label>
			<input type="text" class="text-large required uppercase" placeholder="Ingrese Codigo o Nombre del Producto" id="txtProductoStock">
                        <input type="hidden" id="txtIdProducto" value="">
		</li>
				
	</ul>
</fieldset>
<table>
	<thead>		
                
                <label>Stock Actual-Conteo 1</label><input type="text" id="txtStockActual"  name="idProducto">
				
                <button id="btnActualizarProd">Actualizar</button>
            
                
	</thead>
</table>
