<script type="text/javascript" src="/javascript/notacreditodevolucion.js"></script>

<h2>Facturación: Nota de Crédito Por Devolución</h2>
<fieldset>
    <ul>
        <li>
            <b>Orden de Venta: </b><input type="text" id="txtOrdenVenta" name="txtOrdenVenta" size="100px" placeholder="Orden de Venta">
            <input type="hidden" id="txtIdDevolucion" name="idOrdenVenta" required="required" val="0">
        </li>
    </ul>
</fieldset>

<div id="detalle">
    <a id="imprimir" href="#" ><img src="/imagenes/imprimir.gif"></a>
    <style type="text/css">

        table {
            border: 1px solid;
            border-collapse: collapse;
            border-spacing:0px;
            padding: 0px;


            margin: 0px;
        }

        #tbldetalles > thead > tr > td {
            background: #6cacfb;
            font-weight: bold;
            text-align: center;
        }
    </style>

    <b id="mensaje"></b>
    <table id="tblEncabezado" sytle="magin-botton:0px"></table>
    <table id="tbldetalles">
        <thead>
            <tr>
                <td colspan="6" id="lblFacturaElectronica"></td>
            </tr>
            <tr>
                <th>Numero de Devolucion</th>
                <th>Codigo</th>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Cantidad</th>
                <th>Importe</th>
            </tr>			
        </thead>
        <tbody>
        <td></td>
        </tbody>
        <tfoot>
        <td></td>
        </tfoot>
    </table>
    <button id="btncerrar">Cerrar</button>
    <a href='/facturacion/generarnotacreditodevolucion' id="btnEmitir"><button style="float: right">Emitir Nota de Credito</button></a>
</div>