<script src="/javascript/comisiondeventas.js"></script>
<style>
    .cancelarVendedor {
        cursor: pointer;
    }
    .msg-error {
        color: red;
    }
    #blockPeriodo {
        background: skyblue;
        border: 1px solid black;
        padding: 10px;
    }
</style>
<h2>Resumen :: Comision de Ventas</h2>
<fieldset>
    <form action="/excel/comisiondeventas" method="POST" id="frmComisionVentas" target="_blank">
        <ul>            
            <li>
                <label>Vendedor: </label>
                <input type="text" autofocus="on" size="50" placeholder="Ingrese Nombre de Vendedor" value="" id="txtVendedor">
                <img src="/imagenes/eliminar.gif" class="cancelarVendedor" title="Cancelar" style="display: none;">
                <input type="hidden" id="idVendedor" name="txtidvendedor">
            </li>
            <li>
                <label>Formato: </label>
                <select id="lstFormato">
                    <option value=""> --- Seleccionar --- </option>
                    <option value="1">General</option>
                    <option value="2">Detallado</option>
                </select>
            </li>
            <li>
                <label>Comision: </label>
                <select id="lstComision" name="txtcomision">
                    <option value=""> --- Seleccionar --- </option>
                    <option value="0.5">0.5%</option>
                    <option value="0.25">0.25%</option>
                </select>
            </li>
        </ul>
        <br>
        <ul id="blockPeriodo">
            <li>
                <label>Año:</label>
                <select name="lstAnio" class="required">
                    <option value="2020">2020</option>
                     <option value="2019">2019</option>
                    <option value="2018">2018</option>
                    <option value="2017">2017</option>
                    <option value="2016">2016</option>
                    <option value="2015">2015</option>
                    <option value="2014">2014</option>
                    <option value="2013">2013</option>
                </select>
            </li>
            <li id="mesDetallado">
                <label>Mes: </label>
                <select name="lstMes" class="required">
                    <option value="01">Enero</option>
                    <option value="02">Febrero</option>
                    <option value="03">Marzo</option>
                    <option value="04">Abril</option>
                    <option value="05">Mayo</option>
                    <option value="06">Junio</option>
                    <option value="07">Julio</option>
                    <option value="08">Agosto</option>
                    <option value="09">Septiembre</option>
                    <option value="10">Octubre</option>
                    <option value="11">Noviembre</option>
                    <option value="12">Diciembre</option>
                </select>
            </li>
            <li id="mesGeneral">
                <label>Mes: </label>
                <input type="checkbox" class="chkmes" value="13"> Todo
                <input type="checkbox" class="chkmes" name="chkmes[]" value="01"> Enero
                <input type="checkbox" class="chkmes" name="chkmes[]" value="02"> Febrero
                <input type="checkbox" class="chkmes" name="chkmes[]" value="03"> Marzo
                <input type="checkbox" class="chkmes" name="chkmes[]" value="04"> Abril
                <input type="checkbox" class="chkmes" name="chkmes[]" value="05"> Mayo
                <input type="checkbox" class="chkmes" name="chkmes[]" value="06"> Junio
                <input type="checkbox" class="chkmes" name="chkmes[]" value="07"> Julio
                <input type="checkbox" class="chkmes" name="chkmes[]" value="08"> Agosto
                <input type="checkbox" class="chkmes" name="chkmes[]" value="09"> Septiembre
                <input type="checkbox" class="chkmes" name="chkmes[]" value="10"> Octubre
                <input type="checkbox" class="chkmes" name="chkmes[]" value="11"> Noviembre
                <input type="checkbox" class="chkmes" name="chkmes[]" value="12"> Diciembre
            </li>
        </ul>
        <br>
        <ul>
            <li class="msg-error">                
            </li>
        </ul>
        <br>
        <ul>
            <li>
                <button id="btnConsultarExcel" class="button">Consultar <img style="vertical-align:middle" src="/imagenes/excel.png" width="25" height="25"></button>
            </li>
        </ul>
    </form>
</fieldset>