<?php $idmodulo = 142; require_once 'evalcredenciales.php'; ?>
<script type="text/javascript" src="/javascript/reporteProductoBloque.js" ></script>
<script type="text/javascript" src="/javascript/editarInventario.js"></script>
<h2 style="float:left;padding-bottom: 20px;">MODIFICAR BLOQUE DEL INVENTARIO</h2>
<fieldset>
	<ul>
		<li>

			<?php $cantidadInventario=count($inventario); ?>
			<label>Inventario</label>
			<select id="lstInventario" name="lstInventario" >
                    <?php if($evaluarCredenciales==1){ ?>
                        <?php if($c15_datashet!=$c14_datashet){ ?>
                            <?php for ($i=0; $i <$cantidadInventario ; $i++) { ?>
                                <?php  if ($c14_datashet==1 and  $inventario[$i]['invagrupamiento']==1){ ?>
                                    <option value="<?php echo $inventario[$i]['idinventario']; ?>" ><?php echo $inventario[$i]['codigoinv'].'  del  '.$inventario[$i]['fechainv']; ?></option>
                                <?php } ?>
                                <?php  if ($c14_datashet==0){ ?>
                                    <option value="<?php echo $inventario[$i]['idinventario']; ?>" ><?php echo $inventario[$i]['codigoinv'].'  del  '.$inventario[$i]['fechainv']; ?></option>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                    <?php if($evaluarCredenciales==0){ ?>
                        <?php for ($i=0; $i <$cantidadInventario ; $i++) { ?>
                            <?php  if ($inventario[$i]['invagrupamiento']==1){ ?>
                                <option value="<?php echo $inventario[$i]['idinventario']; ?>" ><?php echo $inventario[$i]['codigoinv'].'  del  '.$inventario[$i]['fechainv']; ?></option>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
				</select>
		</li>
		<li>
			<label>Producto</label>
			<input type="text" size="18" id="txtInventarioProducto">
			<input type="hidden" id="idProducto" value="0">
		</li>
		<li>
			<label>Descripcion</label>
			<input type="text" size="40" id="txtDescripcion" readonly="readonly">
		</li>
		<li>
			<button id="btnBuscar">Buscar</button>
		</li>
	</ul>
</fieldset>

<fieldset>
	<table id="tblDetalle">

	</table>
</fieldset>