<script src="/javascript/proveedornacional_listado.js"></script>
<h2 style="float:left !important;padding-bottom: 20px;width:100%">Listado : Proveedor Nacional</h2>
<form method="POST" action="/proveedornacional/busqueda/">
    <div id="busqueda">Busqueda: <input type="text" id="txtBusqueda" placeholder="RAZON SOCIAL | RUC | DNI" value="<?php echo $texto; ?>" name="txtBusqueda" size="50px">
        <input type="submit" value="Ver">
    </div>
</form>
<table>
    <thead>
        <tr>
            <th colspan="8">Listado de Proveedores Nacionales</th>
            <th><a href="/proveedornacional/nuevo"><img src="/imagenes/iconos/nuevo.gif"></a></th>
        </tr>
        <tr>
            <th>Codigo</th>
            <th>Razon Social</th>
            <th>RUC/DNI</th>
            <th>Actividad Economica</th>
            <th>Produccion o Servicio</th>
            <th>Telefono</th>
            <th>Email</th>
            <th>Situacion</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <?php
        $tam = count($proveedornacional);
        for ($i = 0; $i < $tam; $i++) {
            $fila = "<tr>";
            $fila .= "<td>S" . str_pad($proveedornacional[$i]['idproveedornacional'], 5, "0", STR_PAD_LEFT) . "</td>";
            $fila .= "<td>" . $proveedornacional[$i]['razonsocial'] . "</td>";
            $fila .= "<td>" . $proveedornacional[$i]['rucdni'] . "</td>";
            $fila .= "<td>" . $proveedornacional[$i]['actividadeconomica'] . "</td>";
            $fila .= "<td>" . $ProduccionesIT[$proveedornacional[$i]['produccion']] . "</td>";
            $fila .= "<td>" . $proveedornacional[$i]['telefono'] . "</td>";
            $fila .= "<td>" . $proveedornacional[$i]['email'] . "</td>";
            $fila .= "<td>";
            $fila .= '<select class="classSituacion">
                        <option value=""> -- Seleccione -- </option>';
            for ($j = 1; $j <= count($EstadoSPN); $j++) {
                $fila .= '<option value="' . $j. '"' . ($proveedornacional[$i]['situacion'] == $j ? ' selected' : '') .'>' . $EstadoSPN[$j] . "</option>";
            }
            $fila .= "</select> ";
            $fila .= ' <a href="#" class="classSituacionGuardar" data-id="' . $proveedornacional[$i]['idproveedornacional'] . '" style="display: none"><img src="/imagenes/grabar.gif" width="21" height="21"></a>';
            $fila .= "</td>";
            $fila .= "<td width=\"100px\">
                        <a href=\"/proveedornacional/encuesta/" . $proveedornacional[$i]['idproveedornacional'] . "\" ><img src=\"/imagenes/iconos/facturacion.png\" width='25px'></a> 
                        <a href=\"/proveedornacional/editar/" . $proveedornacional[$i]['idproveedornacional'] . "\" ><img src=\"/imagenes/iconos/editar.gif\"></a> 
                        <a href=\"/proveedornacional/eliminar/" . $proveedornacional[$i]['idproveedornacional'] . "\" class='eliminarProveedorN'><img src=\"/imagenes/iconos/eliminar.gif\"></a>";
            $fila .= "</td>";
            $fila .= "</tr>";
            echo $fila;
            unset($fila);
        }
        ?>	
    </tbody>
    <tfoot>
        <tr><td colspan="9" align="center">
                <?php
                for ($i = 0; $i < $paginacion; $i++) {
                    echo "<a href=\"/proveedornacional/listado/" . ($i + 1) . "\">Pag.  " . ($i + 1) . " </a>";
                    if ($paginacion - $i > 1) {
                        echo "||";
                    }
                }
                ?>
            </td>
        </tr>
    </tfoot>
</table>